#CC=g++
#CFLAGS=-Wall
#objs:=$(wildcard *.cpp)
#targets:=$(objs:.cpp= )
#
#.PHONY:all
#all: $(targets)

#.cpp:
#	@echo $(input)
#	@echo $<
#	@echo $@
#	$(CC) $(CFLAGS) -std=c++11 -o $@ $<
#	./$@ < $@.in > $@.out
#	rm -f $@


